version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: "@types/react-native"
    versions:
    - 0.63.46
    - 0.63.48
    - 0.63.49
    - 0.63.50
    - 0.63.51
    - 0.63.52
    - 0.64.0
    - 0.64.1
    - 0.64.2
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.4
    - 4.1.5
    - 4.2.2
    - 4.2.3
  - dependency-name: lodash
    versions:
    - 4.17.20
